<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="multiactivity" nsURI="http://www.example.org/multiactivity"
    nsPrefix="multiactivity">
  <eClassifiers xsi:type="ecore:EClass" name="Activity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="layouts" lowerBound="1"
        upperBound="-1" eType="#//Layout" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Layout">
    <eStructuralFeatures xsi:type="ecore:EReference" name="views" upperBound="-1"
        eType="#//View" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="View" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NewActivityButton" eSuperTypes="#//View">
    <eStructuralFeatures xsi:type="ecore:EReference" name="activity" lowerBound="1"
        eType="#//Activity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PopupMessageButton" eSuperTypes="#//View">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="message" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TextView" eSuperTypes="#//View"/>
  <eClassifiers xsi:type="ecore:EClass" name="PopupTimeButton" eSuperTypes="#//View"/>
  <eClassifiers xsi:type="ecore:EClass" name="Application">
    <eStructuralFeatures xsi:type="ecore:EReference" name="activities" upperBound="-1"
        eType="#//Activity" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
